US-011 Statistic Generation
willayy/DAT257-Agile pull request #30
Opened 2024-04-18 23:47 UTC by 0-Gixty-0

## What
Created statistical generation based on four forms of selection: 

- Only location selected shows the total number of events reported at selected location for a certain type sorted highest to lowest
- Only type selected shows the total number of events for a certain location for selected type sorted highest to lowest
- Both selections returns the frequency of events of selected type at selected location. Returns only one row in table
- No selection shows error message informing user to make a selection

**Note:** If no event is found an error message is displayed informing the user

## How
User story was completed through creating a new page _statistics_ with selectors for location and event type. Upon clicking the _generate_ button a table with rows described in the above what heading is displayed. Statistic generation rows update automatically once the props passed to the Table.tsx component updates which occurs only once the user has clicked the _generate_ button.

## Why
In order to inform users on crime statistics for locations and event types in a clear and concise way not achieved on the original police website for events.

2024-04-18 23:53 UTC, 0-Gixty-0 commented
Tagging Alexander (@DuchessMuhr)  since we copied his implementation for connecting the search combo boxes to parent component for automatic update. Implementation was copied from changes to the ParentSearchComboBox component. We recommend that issue #29 and issue #24 should be merged first in order to check for possible merge conflicts and resolutions.

Other points of note:

- CSS implementation commit has not yet been pushed since it is still local on Lucas machine. This should be added before reviewers merge the branch into main
- Known issue/missing implementation is that the reset selection option does not clear the combo box selectors. This combined with changing the selector does not remove previously rendered statistics and changes button back to _generate_ state. It is slightly unintuitive, however I found that this issue is small enough that it can be solved later.

2024-04-19 07:38 UTC, maxdreifeldt requested changes
Just a few quick fixes, some of my comments are just straight up questions that might not even require change

Otherwise, good work!

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/app/statistics/page.tsx
> +                <b>Endast typ av event vald:</b> Genom att välja event typ så kan du se vilket kommun eller län eventet har rapporterats flest och minst antal gånger under de senaste 6 månaderna
Just a språkbitch here, but maybe change to 
&lt;b&gt;Endast typ av brott vald:&lt;/b&gt; Genom att välja brottstyp så kan du se vilken kommun eller vilket län brottet har rapporterats flest och minst antal gånger i under de senaste 6 månaderna

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/app/statistics/page.tsx
> +                <b>Endast kommun eller län vald:</b> Genom att välja kommun eller län så kan du se det totala antalet event inrapporterade de senaste 6 månaderna samt vilket typ av event som har rapp
Just a språkbitch here, but maybe change to
&lt;b&gt;Endast kommun eller län vald:&lt;/b&gt; Genom att välja kommun eller län så kan du se det totala antalet brott inrapporterade de senaste 6 månaderna samt vilket typ av brott som har rapporterats flest och minst antal gånger.

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/app/statistics/page.tsx
> +                <b>Event typ och kommun eller län vald:</b> Genom att välja både kommun eller län samt typ av event så ser du hur många event av den typen på den platsen har rapporterats de senaste 6
Just a språkbitch here, but maybe change to
&lt;b&gt;Brottstyp och kommun eller län vald:&lt;/b&gt; Genom att välja både kommun eller län samt brottstyp så ser du hur många brott av den typen som har rapporterats på den platsen de senaste 6 månaderna

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/components/searchComboBox/parentSearchComboBox.tsx
> -    /**
Why was this documentation removed?

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/components/searchComboBox/parentSearchComboBox.tsx
> -    /**
Why was this documentation removed?

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/components/table/table.tsx
> +                            <th scope="col">Typ</th>
språkbitch again:
Maybe change to "Brottstyp" or just "Brott"  or "Typ av brott" or something like that

2024-04-19 07:38 UTC, maxdreifeldt commented on agile-app/src/components/table/table.tsx
> +                            <th scope="col">Antal</th>
Is it clear that this means the amount of reports? I guess it is clear if the 'how-to' from page.tsx is read before, but I still feel like it would bring more clarity if we wrote something like: "Antal inrapportertingar"

2024-04-19 08:26 UTC, willayy requested changes

2024-04-19 08:26 UTC, willayy commented on agile-app/src/app/statistics/page.tsx
> +type CrimeData = (string|string|number)[][]
string | string does nothing since | means or, and can be rewritten to string | number without having any effect

2024-04-19 08:26 UTC, willayy commented on agile-app/src/app/statistics/page.tsx
> +    function sortCrimeDataOnFrequency(crimeData: (string | number)[][]) {
This function could use the CrimeData type instead of redeclaring it

2024-04-19 08:26 UTC, willayy commented on agile-app/src/app/statistics/page.tsx
> +        }
Instead of making a getter functions for all possible combinations (events, location and events & location), you could use the filter function to filter the data more efficiently. Check out the filtering in done in components/listView
https://github.com/willayy/DAT257-Agile/blob/635ff92646a6907c41abfb2e92319ea6586537f5/agile-app/src/components/listView/listView.tsx#L56-L71

2024-04-19 08:26 UTC, willayy commented on agile-app/src/components/table/table.tsx
> +type CrimeData = (string|string|number)[][]
stop redeclaring typealiases, it becomes very annoying to go through all the code and change each instance if change would be needed. It might also lead to silent bugs because you change at one place but not at the other.

2024-04-19 10:01 UTC, 0-Gixty-0 commented on agile-app/src/components/table/table.tsx
> +type CrimeData = (string|string|number)[][]
This type alias is unique to the component and must be included. Is now renamed to CrimeDataRow

2024-04-19 10:02 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +    function sortCrimeDataOnFrequency(crimeData: (string | number)[][]) {
It cannot since it must use the now called CrimeDataRow type to function. It is a type unique to the component and is not the API JSON interface type

2024-04-19 10:02 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +type CrimeData = (string|string|number)[][]
Resolved

2024-04-19 10:08 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +        }
I agree that it may be possible to use the filter function for the data I would still have to count the frequency of the events based on different parameters. Frequency counting based on location, event type, or both is done differently for each case. As I understand the filter function will look for matches and filter accordingly. This would leave me with the events that I'm looking for however there may have to be separate counting functions based on the different selections. Since the code is in a working state at this point I think this should be looked into as an optimization later.

2024-04-19 10:13 UTC, 0-Gixty-0 commented on agile-app/src/components/searchComboBox/parentSearchComboBox.tsx
> -    /**
I performed a ctr+a , ctrl+c, ctrl+v on the entire parentSearchComboBox.tsx file from the branch Alexander was working on. See #29 
I failed to see that the documentation was missing and I presume it was accidentally deleted before I did the operation. I also observe that in the main branch the documentation at that line is missing.

2024-04-19 10:13 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +interface Event {
I was not aware that there was an exportable version. This is now resolved!

2024-04-19 10:16 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +                <b>Endast typ av event vald:</b> Genom att välja event typ så kan du se vilket kommun eller län eventet har rapporterats flest och minst antal gånger under de senaste 6 månaderna
Swedish is not my strongest skill. Resolved!

2024-04-19 10:17 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +                <b>Endast kommun eller län vald:</b> Genom att välja kommun eller län så kan du se det totala antalet event inrapporterade de senaste 6 månaderna samt vilket typ av event som har rapp
Swedish is not my strongest skill. Resolved!

2024-04-19 10:18 UTC, 0-Gixty-0 commented on agile-app/src/app/statistics/page.tsx
> +                <b>Event typ och kommun eller län vald:</b> Genom att välja både kommun eller län samt typ av event så ser du hur många event av den typen på den platsen har rapporterats de senaste 6
Swedish is not my strongest skill. Resolved!

2024-04-25 18:35 UTC, merged