33 getcrimedata is invalid
willayy/DAT257-Agile pull request #50
Opened 2024-05-10 14:31 UTC by willayy

Adding a fetching script to the project directory that can be run using

```bash
npx ts-node src/scripts/fetcher.ts
```
from the ```agile-app``` directory, this script continously and safely fetches data from the [https://polisen.se/om-polisen/om-webbplatsen/oppna-data/api-over-polisens-handelser/](https://polisen.se/om-polisen/om-webbplatsen/oppna-data/api-over-polisens-handelser/) and add its to a local storage located in ```agile-app/public/json```.

The interface for developers getting crime data is still the same but now there is much more data coming in.

2024-05-10 15:27 UTC, Palpat3 reviewed
Is there a reason why we prune the old data instead of just continuously expanding on the data?

2024-05-10 15:36 UTC, Palpat3 commented
> No not really, just an arbitrary limit set to not get too big of a dataset. @Palpat3

Okay then I think everything looks fine. Many things I don't understand but well-structured and clear comments helped me understand in the end, well done getting it done today!

2024-05-10 17:15 UTC, maxdreifeldt commented on agile-app/src/app/api/json/route.ts
> +  combinedData = combinedData.slice(0, -1);
Is this slicing made to remove the last "," added in the replace function in line 12?

2024-05-10 17:23 UTC, willayy commented on agile-app/src/app/api/json/route.ts
> +  combinedData = combinedData.slice(0, -1);
Yes, since every fetch is a list of json objects we need to combine them into a single list.

2024-05-10 19:44 UTC, maxdreifeldt requested changes
Few minor changes, few questions. I dont fully understand all code, but generally it looks good!

2024-05-10 19:44 UTC, maxdreifeldt commented on agile-app/src/scripts/fetcher.ts
> +    console.log("Welcome to fetcher, to to stop the srcript press ctrl + c");
duplicate "to"

2024-05-10 19:44 UTC, maxdreifeldt commented on agile-app/src/scripts/fetcher.ts
> +    console.log("Checking if allowed to call API, last call: " + lastApiCall.toISOString() + ", now: " + (new Date()).toISOString());
Is there a reason to not use the currentDate for printing what the time is now? Just seems unnecessary to create new Date() again.

2024-05-10 19:44 UTC, maxdreifeldt commented on agile-app/src/scripts/fetcher.ts
> +    fs.writeFile(fileName, fileContent, function(err: Error) {
What will happen here when revalidate todays data? Will it delete the old file with that name and create a new one with the same name and adding the "new" data?

2024-05-12 13:06 UTC, willayy commented on agile-app/src/scripts/fetcher.ts
> +    fs.writeFile(fileName, fileContent, function(err: Error) {
Yes that is waht will happen

2024-05-12 13:07 UTC, willayy commented on agile-app/src/scripts/fetcher.ts
> +    console.log("Checking if allowed to call API, last call: " + lastApiCall.toISOString() + ", now: " + (new Date()).toISOString());
Nope, good spot will fix

2024-05-12 13:08 UTC, willayy commented on agile-app/src/scripts/fetcher.ts
> +    console.log("Welcome to fetcher, to to stop the srcript press ctrl + c");
Good spot will fix

2024-05-12 16:44 UTC, maxdreifeldt approved these changes
wiho

2024-05-13 08:02 UTC, merged