Line graph interface is invalid
willayy/DAT257-Agile pull request #60
Opened 2024-05-15 10:15 UTC by Palpat3

## What
Fixed the x-axis on the graph and made sure a longer time period works aswell. Fixed the css for the buttons to match the rest of the site. Fixed the interface so it imports from crimeData

## How
Mapped the months to numbers and added an extra check for the years. I also had to reverse the list. Changed the css to the same as the other buttons. Imported the interface.

## Why
To present a correct line graph with time that works the way time is supposed to work. Because a design is easier to understand and use when everything is standardized. To avoid code repetition.

2024-05-15 15:01 UTC, maxdreifeldt commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +        const monthYearKey = `${monthYear}`;
Why is this variable created? Can't you just use the monthYear variable? I dont understand the difference

2024-05-15 15:06 UTC, maxdreifeldt commented on agile-app/src/app/visualization/page.tsx
>              {showGraph && <LineGraph selectedOptionCrime={selectedOptionCrime} selectedOptionLoc={selectedOptionLoc}/>}
For this part. Maybe use this way instead:

{showGraph ? <LineGraph selectedOptionCrime={selectedOptionCrime} selectedOptionLoc {selectedOptionLoc}/> : null}
It works like this:
(condition ? expr1 : expr2)
where expr1 happens if the condition is true.

This is the way we've written conditional html before, or at least in the statistic page

2024-05-15 15:27 UTC, maxdreifeldt commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +        return monthsMap[aMonth] - monthsMap[bMonth];
Why are not months and years sorted in the same order?
2024-02 should come before 2024-01 since the month is higher, the same way as 2024-01 should come before 2023-12 since the year is higher. I dont understand why you take a - b for year and b - a for months

2024-05-15 15:36 UTC, maxdreifeldt commented on agile-app/src/components/lineGraph/lineGraph.tsx
>                  data: labels.map(month => groupedData[month] || 0), // Ensure all months have a value
I dont think this part works as expected
If you take a look at "alkohollagen", you'll see that it looks like this: {showGraph ? ![image](https://github.com/willayy/DAT257-Agile/assets/59491282/9b4492e3-d34a-4aad-b2fd-4e4869af78cd)

As you can see, the months does not work.
This is because if you dont have any data for a specific crimeType for a month, there will be no instance of that specific monthYear, meaning that that monthYear does not get added to groupedData directory (or whatever it is called in TS). Then it does not get added into the allMonths set, and then not into the labels array, and therefore not inte the dataset data.

2024-05-16 14:09 UTC, Palpat3 commented on agile-app/src/app/visualization/page.tsx
> +            <div>
Was necessary before, removed now.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
>      const filteredCrimeData = data.filter(crime => {
Done.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
>      const chartRef = useRef<HTMLCanvasElement>(null);
Done.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +        const monthYearKey = `${monthYear}`;
It used to do something else and was left behind when changed. I have fixed it.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/app/visualization/page.tsx
>              {showGraph && <LineGraph selectedOptionCrime={selectedOptionCrime} selectedOptionLoc={selectedOptionLoc}/>}
Done.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +        return monthsMap[aMonth] - monthsMap[bMonth];
Fixed.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
>                  data: labels.map(month => groupedData[month] || 0), // Ensure all months have a value
Fixed so all months are included even if they are empty.

2024-05-16 14:10 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
>          }
I do not get this error so it is hard to fix.

2024-05-16 21:21 UTC, maxdreifeldt requested changes
Two small changes, but otherwise looks good

2024-05-16 21:21 UTC, maxdreifeldt commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +    const currentDate = new Date(earliestDate);
should this not be:
let currentDate = new Date(earliestDate), since it changes later?

2024-05-16 21:21 UTC, maxdreifeldt commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +    const latestDate = new Date(Math.max(...data.map(crime => new Date(crime.datetime).getTime())));
Would this be a better way to write it?
```typescript
const dates = data.map(crime => new Date(crime.datetime));
const earliestDate = new Date(Math.min(...dates));
const latestDate = new Date(Math.max(...dates));
```

It seems unneccesary to convert all crime.datetime to dates twice. this way, it only gets done once. Seems more efficent

2024-05-16 23:19 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +    const currentDate = new Date(earliestDate);
Done.

2024-05-16 23:19 UTC, Palpat3 commented on agile-app/src/components/lineGraph/lineGraph.tsx
> +    const latestDate = new Date(Math.max(...data.map(crime => new Date(crime.datetime).getTime())));
Yes but with a minor change, it still needs getTime() or the types won't match.

2024-05-16 23:21 UTC, merged