43 us 021 implement unit tests
willayy/DAT257-Agile pull request #64
Opened 2024-05-16 14:40 UTC by willayy

Implemented 5 test suites testing the backend and some frontend pages.

2024-05-16 23:25 UTC, Palpat3 commented on agile-app/__tests__/testDataFetching.test.ts
> +    expect(crimeData[0]).toHaveProperty('location');
Is there a reason for not testing the name and gps property inside the location?

2024-05-16 23:26 UTC, Palpat3 commented on agile-app/__tests__/testLineGraph.test.tsx
> +        expect(chart).toHaveAttribute('width', '400');
I think these are not up to date, the new size of the linegraph should be 600 by 600

2024-05-16 23:34 UTC, Palpat3 requested changes
Nothing that looks weird but some minor things I noticed and one test that is outdated

2024-05-17 10:12 UTC, jmarkusson commented
Looks good, Why is there no tests on the heat map page?

2024-05-17 12:06 UTC, willayy commented on agile-app/__tests__/testLineGraph.test.tsx
> +        expect(chart).toHaveAttribute('width', '400');
I fixed this

2024-05-17 12:08 UTC, willayy commented on agile-app/__tests__/testDataFetching.test.ts
> +    expect(crimeData[0]).toHaveProperty('location');
Its already sufficiently validated

2024-05-17 12:09 UTC, willayy commented
@Palpat3 I have fixed the points you raised

2024-05-17 12:10 UTC, willayy commented
@jmarkusson Its because it uses functions that can't be used with jest

2024-05-17 12:26 UTC, merged